### ISSUE TITLE
Ability to connect from the MoUI directly to the Serial without the bridge

### ISSUE THREAD

**Issue by feiteira** [MOonRails/MoUI_onRails#2]
It should be possible to connect from the MoUI directly to the Serial without the bridge. This would greatly simplify getting started.
Ideally I would be interesting to keep also the TCP/IP option available so that in the future other devices/implementations may use it.

Happy New Year! :+1:

**Comment by phil333** [comment]
Connection now working on the serial port. Sending of commands possible. Reception of data will be available with the next release.

**Comment by phil333** [comment]
now implemented, both for reception and transmission
