### ISSUE TITLE
I cannot start the latest release on Windows

### ISSUE THREAD

**Issue by feiteira** [MOonRails/MoUI_onRails#3]
I tried to run the binary as it comes, and it complained that libwinpthread-1.dll was missing.
I copied the DLL from the version 1.0 zip file into the MOUI folder and then another error happened:
![capture1](https://user-images.githubusercontent.com/668778/35731433-ced06c06-0815-11e8-8712-5f2aa41f023c.PNG)

**Comment by phil333** [comment]
Thank you for this tip, I came across this recently as well, and it is basically an issue for systems that do not have the gcc compiler libraries installed or linked in the windows $PATH. I will add them with the next release, which will be available in the next 3 days, including the qserial communication

**Comment by phil333** [comment]
gcc library issue, fixed with the latest release
